"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u$lf@ir3#ew&=htlr$vm_ar6w23z=+_0gnkwq1e3*r#d1pqagu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'social_django',
]


AUTHENTICATION_BACKENDS = (
    'social_core.backends.linkedin.LinkedinOpenIdConnect',  # Use this instead of open_id_connect
    'django.contrib.auth.backends.ModelBackend',  # Default auth
)

# LinkedIn OpenID Connect settings
SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_KEY = "77mtrb05eysogq"
SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_SECRET = "WPL_AP1.lEiXsSByLAK6JzER.aB1wGg=="
SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_SCOPE = ["openid", "profile", "email"]
SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_REDIRECT_URI = "http://127.0.0.1:8000/auth/complete/linkedin-openidconnect/"
# SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_SCOPE = ["openid", "profile", "email"]
# SOCIAL_AUTH_LINKEDIN_OPENIDCONNECT_EXTRA_DATA = [
#     ("sub", "id"),
#     ("name", "full_name"),
#     ("email", "email"),
# ]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# SOCIAL_AUTH_OPENID_CONNECT_ENDPOINT = "https://www.linkedin.com/oauth/v2"
# SOCIAL_AUTH_OPENID_CONNECT_KEY = "77mtrb05eysogq"
# SOCIAL_AUTH_OPENID_CONNECT_SECRET = "WPL_AP1.lEiXsSByLAK6JzER.aB1wGg=="
# SOCIAL_AUTH_OPENID_CONNECT_SCOPE = ["openid", "profile", "email"]
# SOCIAL_AUTH_OPENID_CONNECT_EXTRA_DATA = [
#     ("sub", "id"),
#     ("name", "full_name"),
#     ("email", "email"),
# ]

# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
